name: Publish documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: { }

jobs:
  build-documentation:
    name: "Build documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push commits to gh-pages branch
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # tag=v5.7.0
        with:
          distribution: temurin
          java-version: '25'
      - name: Build with Maven
        run: mvn -B --no-transfer-progress package
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # tag=v4.9.0
        with:
          branch: gh-pages
          folder: target/reports/apidocs
