name: Report PR Test Coverage

on:
  workflow_run:
    workflows:
    - Maven CI
    types:
    - completed

permissions: { }

jobs:
  publish:
    name: Report Coverage
    runs-on: ubuntu-latest
    if: |-
      github.event.workflow_run.event == 'pull_request'
        && github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download PR test coverage report
      uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # tag=v4.2.0
      with:
        name: pr-test-coverage-report-java-21
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
    - name: Report Coverage to Codacy
      run: |-
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          --project-token ${{ secrets.CODACY_PROJECT_TOKEN }} \
          --commit-uuid ${{ github.event.workflow_run.head_sha }} \
          --coverage-reports ./jacoco.xml \
          --language Java
